CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS worker_db;
CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS payment_db;

CREATE USER IF NOT EXISTS 'shashank'@'%' IDENTIFIED BY 'Shashank@123';
GRANT ALL PRIVILEGES ON *.* TO 'shashank'@'%';
FLUSH PRIVILEGES;
